---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(dplyr)
library(ggplot2)
library(magrittr)
library(glue)
library(utils)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get a message with a fur color
    
You can get a message with the fur color of interest with `get_message_fur_color()`.

```{r function-get_message_fur_color}
#' Get a message with the fur color of interest
#'
#' @param primary_fur_color Character. The primary fur color of interest
#' @importFrom glue glue
#' 
#' @return Used for side effect. Outputs a message in the console
#' @export
#'
#' @examples
get_message_fur_color <- function(primary_fur_color) {
  message(glue("We will focus on {primary_fur_color} squirrels"))
}
```
  
```{r example-get_message_fur_color}
get_message_fur_color(primary_fur_color = "Cinnamon")
```
  
```{r tests-get_message_fur_color}
test_that("get_message_fur_color works", {
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Cinnamon"), 
    regexp = "We will focus on Cinnamon squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Gray"), 
    regexp = "We will focus on Gray squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Black"), 
    regexp = "We will focus on Black squirrels"
  )
  
})

test_that("get_message_fur_color doesnt works", {
  
  expect_error(
   get_message_fur_color()
  )
  
})
```
  

```{r function-study_activity} 

#'Study the activities of the squirrels given a primary fur color
#'
#' @param df_squirrels_act Data frame. A dataset with the activities of the squirrels. This dataset mush have at leat these 4 columns: "age", "primary_fur_color", "activity", "counts".
#' @param col_primary_fur_color Character. The color of the primary fur color of interest. Only the squirrels with this primary fur color will be considered in the analysis.
#' 
#' @importFrom dplyr filter
#' @importFrom ggplot2 ggplot aes geom_col scale_fill_manual labs
#' @importFrom magrittr %>% 
#' @importFrom glue glue
#'
#' @return A list of two named elements. The first one is the filtered table. The second one is the ggplot.
#' @export
#'
#' @examples
study_activity <- function(df_squirrels_act, col_primary_fur_color) {
  
  # check if we have the right column
  check_squirrel_data_integrity(df_squirrels_act)
  
  # check if we provide the right color
  check_primary_color_is_ok(col_primary_fur_color)
  
  if(isFALSE(is.data.frame(df_squirrels_act))) {
    stop("df_squirrels_act is not a data frame")
  }
  
  if(isFALSE(is.character(col_primary_fur_color))) {
    stop("col_primary_fur_color is not a character vector")
  }
  
  table <- df_squirrels_act %>% 
    filter(primary_fur_color == col_primary_fur_color) 
  
  print(dput(table))
  
  csv_file <- save_as_csv(this_data_frame = table,  
                csv_destination = "study_activity.csv")

  graph <- table %>% 
    ggplot() +
    aes(x = activity, y = counts, fill = age) +
    geom_col() +
    labs(x = "Type of activity",
         y = "Number of observations",
         title = glue("Type of activity by age for {tolower(col_primary_fur_color)} squirrels")) +
    scale_fill_manual(name = "Age",
                      values = c("#00688B", "#00BFFF"))
  
  return(list(table = table, graph = graph, csv_file = csv_file))
}

```
  
```{r example-study_activity}
data("nyc_squirrels_act_sample_15")
study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
                                     col_primary_fur_color = "Gray")
```
  
```{r tests-study_activity}
test_that("study_activity() works", {
    expect_message(study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
                                     col_primary_fur_color = "Gray"),
                 regexp = "All primary fur colors are ok") 
     # expect_error(study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
     #                                  col_primary_fur_color = ""),
     #              regexp = "All primary fur colors are ok")
  
  
  
})
```
  
  

```{r function-save_as_csv}
#' Save a dataset as a csv file 
#' 
#' @param nyc_squirrels_act_sample_15 a dataframe to write to csv
#' @param csv_name a string that corresponds to the path of the file to be created
#' 
#' @return a string: the full path of the created csv as output
#' with the function write.csv2() from {utils} package to the specified path
#' 
#' @importFrom utils write.csv
#' 
#' @export
save_as_csv<- function(this_data_frame = nyc_squirrels_act_sample_15, csv_destination  = "temp.csv"){
  
  # check for "csv", class and existing dir
  expect_true(grepl("csv$",csv_destination))
  expect_true(inherits(this_data_frame, "data.frame"))
  expect_true(dir.exists(dirname(csv_destination)))
  
  # set the pathname
  csv_path = normalizePath(csv_destination)
  
  # write the file
  utils::write.csv2(this_data_frame, csv_path)  
  
  # return it
  return(csv_path)
}

```
  
```{r example-save_as_csv}
my_temp_folder <- tempfile(pattern = "savecsv")
dir.create(my_temp_folder)

# ok: the .csv file is saved in the current project
nyc_squirrels_act_sample_15 %>% save_as_csv(file.path(my_temp_folder, "output.csv"))

# ok: the .csv file is saved and the file opens
nyc_squirrels_act_sample_15 %>% save_as_csv(file.path(my_temp_folder, "output.csv")) %>% browseURL() 

# error: the extension of the file to create is not the right one
# iris %>% save_as_csv(file.path(my_temp_folder, "output.xlsx")) 

# error: the function is not applied to a data.frame
# NULL %>% save_as_csv(file.path(my_temp_folder, "output.csv"))

# error: the path where the file should be saved does not exist
# iris %>% save_as_csv(file.path(my_temp_folder, "does/no/exist.csv")) 

# need to unlink
# ...

```
  
```{r tests-save_as_csv()}
test_that("save_as_csv() works", {
  expect_true(inherits(save_as_csv(), "function")) 
  
  # .. and unlink
})
```



  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_study_squirrels.Rmd", 
               vignette_name = "Study the squirrels",
               overwrite = TRUE)
```
