# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

test_that("get_message_fur_color works", {
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Cinnamon"), 
    regexp = "We will focus on Cinnamon squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Gray"), 
    regexp = "We will focus on Gray squirrels"
  )
  
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Black"), 
    regexp = "We will focus on Black squirrels"
  )
  
})

test_that("get_message_fur_color doesnt works", {
  
  expect_error(
   get_message_fur_color()
  )
  
})

test_that("study_activity() works", {
    expect_message(study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
                                     col_primary_fur_color = "Gray"),
                 regexp = "All primary fur colors are ok") 
     # expect_error(study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
     #                                  col_primary_fur_color = ""),
     #              regexp = "All primary fur colors are ok")
  
  
  
})
