# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_squirrel_data_integrity works", {
  
  # Everything is ok
  my_data_squirrels <- readr::read_csv(system.file("nyc_squirrels_sample.csv", package = "squirrels"))
  
  expect_message(check_squirrel_data_integrity(my_data_squirrels), 
                 regexp = "All primary fur colors are ok") 
  
  # Error : no primary_fur_color column in the dataset
  my_data_squirrels_wrong_colname <- my_data_squirrels %>% 
    dplyr::rename(primary_color = primary_fur_color)

  expect_error(check_squirrel_data_integrity(my_data_squirrels_wrong_colname), 
               regexp = "There is no primary_fur_color in this dataset")
  
  # Error : not allowed colors in the primary_fur_color column
  my_data_squirrels_wrong_colors <- my_data_squirrels %>% 
     dplyr::mutate(primary_fur_color = stringr::str_to_lower(primary_fur_color))
  
  expect_error(check_squirrel_data_integrity(my_data_squirrels_wrong_colors), 
               regexp = "The vector of primary fur color contains not allowed colors")
  
})
