# WARNING - Generated by {fusen} from /dev/flat_check_data.Rmd: do not edit by hand

test_that("check_primary_color_is_ok works", {
  
  expect_true(check_primary_color_is_ok(string = c("Black", "Cinnamon", NA))) 
  
  expect_true(check_primary_color_is_ok(string = c("Gray", "Cinnamon", "Gray")))
  
  expect_error(check_primary_color_is_ok(string = c("Gray", "Cinnamon", "Blue")),
               regexp = "The vector of primary fur color contains not allowed colors")
  
})
