# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Get a message with the fur color of interest
#'
#' @param primary_fur_color Character. The primary fur color of interest
#' @importFrom glue glue
#' 
#' @return Used for side effect. Outputs a message in the console
#' @export
#'
#' @examples
#' get_message_fur_color(primary_fur_color = "Cinnamon")
get_message_fur_color <- function(primary_fur_color) {
  message(glue("We will focus on {primary_fur_color} squirrels"))
}


#'Study the activities of the squirrels given a primary fur color
#'
#' @param df_squirrels_act Data frame. A dataset with the activities of the squirrels. This dataset mush have at leat these 4 columns: "age", "primary_fur_color", "activity", "counts".
#' @param col_primary_fur_color Character. The color of the primary fur color of interest. Only the squirrels with this primary fur color will be considered in the analysis.
#' 
#' @importFrom dplyr filter
#' @importFrom ggplot2 ggplot aes geom_col scale_fill_manual labs
#' @importFrom magrittr %>% 
#' @importFrom glue glue
#'
#' @return A list of two named elements. The first one is the filtered table. The second one is the ggplot.
#' @export
#'
#' @examples
#' data("nyc_squirrels_act_sample_15")
#' study_activity(df_squirrels_act = nyc_squirrels_act_sample_15, 
#'                                      col_primary_fur_color = "Gray")
study_activity <- function(df_squirrels_act, col_primary_fur_color) {
  
  # check if we have the right column
  check_squirrel_data_integrity(df_squirrels_act)
  
  # check if we provide the right color
  check_primary_color_is_ok(col_primary_fur_color)
  
  if(isFALSE(is.data.frame(df_squirrels_act))) {
    stop("df_squirrels_act is not a data frame")
  }
  
  if(isFALSE(is.character(col_primary_fur_color))) {
    stop("col_primary_fur_color is not a character vector")
  }
  
  table <- df_squirrels_act %>% 
    filter(primary_fur_color == col_primary_fur_color)
    
  graph <- table %>% 
    ggplot() +
    aes(x = activity, y = counts, fill = age) +
    geom_col() +
    labs(x = "Type of activity",
         y = "Number of observations",
         title = glue("Type of activity by age for {tolower(col_primary_fur_color)} squirrels")) +
    scale_fill_manual(name = "Age",
                      values = c("#00688B", "#00BFFF"))
  
  return(list(table = table, graph = graph))
}

